insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Chateau Bonnet', '518-71-427', 77.4, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Water', 'Aquafina Vitamin', '298-97-852', 16.94, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Soup', 'Verve - Chipotle Chicken', '312-45-974', 64.86, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Pastry', 'French Mini Assorted', '031-61-533', 75.49, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Pan Grease', 'Humm', '840-29-058', 93.26, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Nut', 'Macadamia', '692-58-108', 38.75, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'White, French Cross', '433-17-606', 53.74, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Rhine Riesling Wolf Blass', '032-34-166', 73.4, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Compound', 'Pear', '775-99-201', 3.08, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Cake', 'Lemon Chiffon', '853-11-281', 84.45, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Lamb', 'Whole, Fresh', '609-52-863', 69.66, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Pasta', 'Fusili Tri - Coloured', '858-01-728', 36.64, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Cake', 'Cake Sheet Macaroon', '506-81-933', 54.56, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Shrimp', 'Black Tiger 16/20', '570-61-019', 12.34, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Cousino Macul Antiguas', '881-16-689', 86.18, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Ham', 'Black Forest', '484-96-900', 66.28, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Basil', 'Dry, Rubbed', '198-35-635', 67.33, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Cookie Choc', 'Humm', '589-35-939', 85.63, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Eggplant', 'Asian', '977-28-859', 70.09, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Pop Shoppe', 'Cream Soda', '191-03-332', 35.49, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Sobe', 'Liz Blizz', '020-56-353', 98.6, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Energy', 'Drink', '905-72-886', 98.92, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Bread Roll', 'Canadian Dinner', '221-58-730', 17.55, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Huck Towels', 'White', '038-40-565', 67.61, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Valpolicella Masi', '071-23-944', 20.92, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Fib N9', 'Prague Powder', '149-92-933', 36.7, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Red, Lurton Merlot De', '939-07-063', 92.39, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Veal', 'Bones', '201-27-645', 56.48, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'Segura Viudas Aria Brut', '147-33-316', 85.2, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Muffin Mix', 'Carrot', '810-50-713', 75.1, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Gelatine', 'Powder', '904-99-842', 70.21, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Cheese', 'Bakers Cream Cheese', '856-19-149', 33.74, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Spaghetti', 'Squash', '278-36-989', 54.94, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Latex Rubber', 'Gloves Size 9', '204-86-259', 64.9, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Flounder', 'Fresh', '885-01-405', 63.05, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Soup', 'Boston Clam Chowder', '046-73-842', 3.38, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Container', 'Clear 16 Oz', '803-99-469', 37.04, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Squash', 'Pattypan, Yellow', '176-16-107', 59.78, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Russian Prince', 'Humm', '912-10-980', 18.91, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Lamb', 'Loin, Trimmed, Boneless', '359-41-062', 70.66, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Bread', 'Raisin Walnut Pull', '026-73-969', 46.74, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Turkey Tenderloin', 'Frozen', '586-33-892', 97.14, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Tea', 'Darjeeling, Azzura', '595-14-514', 40.01, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Mustard', 'Dry, Powder', '761-29-707', 92.73, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Bread', 'Granary Small Pull', '306-71-328', 96.49, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Cilantro / Coriander', 'Fresh', '937-78-691', 25.51, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Apple', 'Delicious, Red', '997-17-952', 38.89, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Dr. Pepper', '355ml', '432-77-834', 25.96, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Mustard', 'Individual Pkg', '558-89-540', 97.22, null);
insert into Product (product_id, product_name, product_desc, product_ref, product_price, category_cat_id) values (null, 'Wine', 'White Cab Sauv.on', '283-17-301', 75.84, null);
